services:
  mongodb-service:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    networks:
      - backend
  config-service:
    container_name: config-service
    build: ./config-service
    ports:
      - "10100:10100"
    restart: always
    healthcheck:
      test: "curl --fail --silent localhost:10100/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 30s
      retries: 5
    depends_on:
      - mongodb-service
    networks:
      - backend
    environment:
      - EUREKA_HOST=registry-service
      - EUREKA_PORT=10050
  registry-service:
    container_name: registry-service
    build: ./registry-service
    ports:
      - "10050:10050"
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    networks:
      - backend
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:10100
  gateway-service:
    container_name: gateway-service
    build: ./gateway-service
    ports:
      - "10060:10060"
    restart: always
    healthcheck:
      test: "curl --fail --silent localhost:10060/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - registry-service
    networks:
      - backend
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:10100
      - EUREKA_HOST=registry-service
      - EUREKA_PORT=10050
  uaa-service:
    container_name: uaa-service
    build: ./uaa-service
    ports:
      - "10020:10020"
    restart: always
    depends_on:
      gateway-service:
        condition: service_healthy
    networks:
      - backend
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:10100
      - EUREKA_HOST=registry-service
      - EUREKA_PORT=10050
      - SPRING_DATA_MONGODB_HOST=mongodb-service
  recipe-service:
    container_name: recipe-service
    build: ./recipe-service
    ports:
      - "10010:10010"
    restart: always
    depends_on:
      gateway-service:
        condition: service_healthy
    networks:
      - backend
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:10100
      - EUREKA_HOST=registry-service
      - EUREKA_PORT=10050
      - SPRING_DATA_MONGODB_HOST=mongodb-service

networks:
  backend:
    driver: bridge