server:
  port: 10100
spring:
  application:
    name: config-service
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/Fandoren/recipe-config.git
          search-paths:
            - spec/config/default
          force-pull: false
          ignoreLocalSshSettings: false

eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 15
    service-url:
      defaultZone: http://${DOCKER_HOST:localhost}:10050/eureka/
